name = "forum-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "forum-db"
database_id = "fb2ba8ba-07a2-4d3a-bbf0-c9789b5a60c8"
migrations_dir = "migrations"

[dev]
port = 8080
local_protocol = "http"
ip = "0.0.0.0"
