name = "forum-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "forum-db"
database_id = "c0049037-8b94-4fae-8973-d95977bf2ae7"
migrations_dir = "migrations"

[assets]
directory = "../forum/dist/public"
not_found_handling = "single-page-application"
binding = "ASSETS"

[dev]
port = 8080
local_protocol = "http"
ip = "0.0.0.0"
