kind = "web"
previewPath = "/"
title = "Forum"
version = "1.0.0"
id = "artifacts/forum"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22557

[services.development]
run = "pnpm --filter @workspace/forum run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/forum", "run", "build" ]
publicDir = "artifacts/forum/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22557"
BASE_PATH = "/"
